run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - dogsled
    - errcheck
    - copyloopvar
    - exhaustive
    - goconst
    - gocritic
    - gofmt
    - goimports
    - mnd
    - gocyclo
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - nakedret
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

linters-settings:
  gocyclo:
    min-complexity: 15

  revive:
    confidence: 0.8

  gofmt:
    simplify: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude:
    - "should have comment"
    - "cyclomatic complexity"
