// Code generated by MockGen. DO NOT EDIT.
// Source: app/service/message_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	model "messaging-system/app/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	primitive "go.mongodb.org/mongo-driver/bson/primitive"
)

// MockIRepository is a mock of IRepository interface.
type MockIRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIRepositoryMockRecorder
}

// MockIRepositoryMockRecorder is the mock recorder for MockIRepository.
type MockIRepositoryMockRecorder struct {
	mock *MockIRepository
}

// NewMockIRepository creates a new mock instance.
func NewMockIRepository(ctrl *gomock.Controller) *MockIRepository {
	mock := &MockIRepository{ctrl: ctrl}
	mock.recorder = &MockIRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRepository) EXPECT() *MockIRepositoryMockRecorder {
	return m.recorder
}

// GetMessages mocks base method.
func (m *MockIRepository) GetMessages(ctx context.Context, status string, limit int) ([]model.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessages", ctx, status, limit)
	ret0, _ := ret[0].([]model.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessages indicates an expected call of GetMessages.
func (mr *MockIRepositoryMockRecorder) GetMessages(ctx, status, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessages", reflect.TypeOf((*MockIRepository)(nil).GetMessages), ctx, status, limit)
}

// MarkMessageAsSent mocks base method.
func (m *MockIRepository) MarkMessageAsSent(ctx context.Context, messageID primitive.ObjectID, webhookMessageID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkMessageAsSent", ctx, messageID, webhookMessageID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkMessageAsSent indicates an expected call of MarkMessageAsSent.
func (mr *MockIRepositoryMockRecorder) MarkMessageAsSent(ctx, messageID, webhookMessageID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkMessageAsSent", reflect.TypeOf((*MockIRepository)(nil).MarkMessageAsSent), ctx, messageID, webhookMessageID)
}
