// Code generated by MockGen. DO NOT EDIT.
// Source: app/handler/handler.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	model "messaging-system/app/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIMessageProcessor is a mock of IMessageProcessor interface.
type MockIMessageProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockIMessageProcessorMockRecorder
}

// MockIMessageProcessorMockRecorder is the mock recorder for MockIMessageProcessor.
type MockIMessageProcessorMockRecorder struct {
	mock *MockIMessageProcessor
}

// NewMockIMessageProcessor creates a new mock instance.
func NewMockIMessageProcessor(ctrl *gomock.Controller) *MockIMessageProcessor {
	mock := &MockIMessageProcessor{ctrl: ctrl}
	mock.recorder = &MockIMessageProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIMessageProcessor) EXPECT() *MockIMessageProcessorMockRecorder {
	return m.recorder
}

// GetSentMessages mocks base method.
func (m *MockIMessageProcessor) GetSentMessages(ctx context.Context, limit int) ([]model.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSentMessages", ctx, limit)
	ret0, _ := ret[0].([]model.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSentMessages indicates an expected call of GetSentMessages.
func (mr *MockIMessageProcessorMockRecorder) GetSentMessages(ctx, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSentMessages", reflect.TypeOf((*MockIMessageProcessor)(nil).GetSentMessages), ctx, limit)
}

// Start mocks base method.
func (m *MockIMessageProcessor) Start(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start", ctx)
}

// Start indicates an expected call of Start.
func (mr *MockIMessageProcessorMockRecorder) Start(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockIMessageProcessor)(nil).Start), ctx)
}

// Stop mocks base method.
func (m *MockIMessageProcessor) Stop(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop", ctx)
}

// Stop indicates an expected call of Stop.
func (mr *MockIMessageProcessorMockRecorder) Stop(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockIMessageProcessor)(nil).Stop), ctx)
}
