// Code generated by MockGen. DO NOT EDIT.
// Source: app/processor/message_processor.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	dto "messaging-system/app/dto"
	model "messaging-system/app/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	primitive "go.mongodb.org/mongo-driver/bson/primitive"
)

// MockIMessageService is a mock of IMessageService interface.
type MockIMessageService struct {
	ctrl     *gomock.Controller
	recorder *MockIMessageServiceMockRecorder
}

// MockIMessageServiceMockRecorder is the mock recorder for MockIMessageService.
type MockIMessageServiceMockRecorder struct {
	mock *MockIMessageService
}

// NewMockIMessageService creates a new mock instance.
func NewMockIMessageService(ctrl *gomock.Controller) *MockIMessageService {
	mock := &MockIMessageService{ctrl: ctrl}
	mock.recorder = &MockIMessageServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIMessageService) EXPECT() *MockIMessageServiceMockRecorder {
	return m.recorder
}

// GetMessages mocks base method.
func (m *MockIMessageService) GetMessages(ctx context.Context, status string, limit int) ([]model.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessages", ctx, status, limit)
	ret0, _ := ret[0].([]model.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessages indicates an expected call of GetMessages.
func (mr *MockIMessageServiceMockRecorder) GetMessages(ctx, status, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessages", reflect.TypeOf((*MockIMessageService)(nil).GetMessages), ctx, status, limit)
}

// MarkMessageAsSent mocks base method.
func (m *MockIMessageService) MarkMessageAsSent(ctx context.Context, messageID primitive.ObjectID, webhookMessageID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkMessageAsSent", ctx, messageID, webhookMessageID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkMessageAsSent indicates an expected call of MarkMessageAsSent.
func (mr *MockIMessageServiceMockRecorder) MarkMessageAsSent(ctx, messageID, webhookMessageID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkMessageAsSent", reflect.TypeOf((*MockIMessageService)(nil).MarkMessageAsSent), ctx, messageID, webhookMessageID)
}

// MockIClient is a mock of IClient interface.
type MockIClient struct {
	ctrl     *gomock.Controller
	recorder *MockIClientMockRecorder
}

// MockIClientMockRecorder is the mock recorder for MockIClient.
type MockIClientMockRecorder struct {
	mock *MockIClient
}

// NewMockIClient creates a new mock instance.
func NewMockIClient(ctrl *gomock.Controller) *MockIClient {
	mock := &MockIClient{ctrl: ctrl}
	mock.recorder = &MockIClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIClient) EXPECT() *MockIClientMockRecorder {
	return m.recorder
}

// SendMessage mocks base method.
func (m *MockIClient) SendMessage(request *dto.MessageRequest) (*dto.MessageResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", request)
	ret0, _ := ret[0].(*dto.MessageResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockIClientMockRecorder) SendMessage(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockIClient)(nil).SendMessage), request)
}

// MockICacheService is a mock of ICacheService interface.
type MockICacheService struct {
	ctrl     *gomock.Controller
	recorder *MockICacheServiceMockRecorder
}

// MockICacheServiceMockRecorder is the mock recorder for MockICacheService.
type MockICacheServiceMockRecorder struct {
	mock *MockICacheService
}

// NewMockICacheService creates a new mock instance.
func NewMockICacheService(ctrl *gomock.Controller) *MockICacheService {
	mock := &MockICacheService{ctrl: ctrl}
	mock.recorder = &MockICacheServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICacheService) EXPECT() *MockICacheServiceMockRecorder {
	return m.recorder
}

// Set mocks base method.
func (m *MockICacheService) Set(ctx context.Context, key string, value interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockICacheServiceMockRecorder) Set(ctx, key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockICacheService)(nil).Set), ctx, key, value)
}
